### PR TITLE
Updated readme file to include usage and installation instructions

### PR DESCRIPTION
**Pull request by lafe**
Usage and installations instructions are based on my experience with the plugin

### CODE REVIEW

**Comment by gautamsi** [comment]
which of the component required Python and C++ (vs)? was it during npm install?

I may have to clean up some of the dependencies not being used. Which may eliminate the need of python and C++ libraries.

**Comment by lafe** [comment]
If I remember correctly, it was during the npm install of the sample. npm install and jspm install of the "root" folder did not require any additional prerequistes on my machine

**Comment by gautamsi** [comment]
looks like this is due to dev dependency of OfficeDev/OfficeFabricUI, I am not planning to us it as part of this codebase, this is only for my reference in porting/conversion. Will remove this dependency in next commit. Can you send me another pull request with readme update without Prerequistes section.

**Comment by gautamsi** [comment]
only css is being used, Will update sample css reference to use cdn.

**Comment by lafe** [comment]
Created new pull request #5 to include the requested changes

**Pull request closed without merging**
